**Numpy**

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
import numpy as np
my_list = [1,2,3,4,5]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
import numpy as np
array = np.array([1,2,3,4,5,6])
print(array)
array = array*2      # Numpy supports Vectorisation
print(array)
print(type(array))

[1 2 3 4 5 6]
[ 2  4  6  8 10 12]
<class 'numpy.ndarray'>


**1. Multidimensional** **Array**

In [ ]:
import numpy as np
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
print(array.shape)
print(array.ndim)

(3, 3, 3)
3


In [ ]:
# CHAIN Indexing
import numpy as np
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

print(array[0][2][0])     # array(depth, No.of Rows, No.of Columns)
        #or
#print(array[0,0,1])      # Multidimensional indexing

#words printing
word = array[0,0,0] + array[0,1,0] + array[0,2,2]
print(word)
word2 = array[0,2,1] + array[0,1,1] + array[1,0,2] + array[1,0,2] + array[1,1,2]
print(word2)
word3 = array[0,2,0] + array[2,0,2] + array[2,2,0] + array[2,0,0]
print(word3)

G
ADI
HELLO
GUYS


**2. Slicing**

In [ ]:
import numpy as np
# Matrix of data 2D Array
#array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
                    #OR    (we can write in both ways both are same)

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# Rows Selection.
# 1. array[start : end : step]

print("For 1st Row:",array[0])   # use for getting 1 row
print("For 2nd Row:",array[2])

# 2. Print range of elements
print("Range of elements:")
print(array[0:3])

# 3. Print range with steps
print("Range of elements with steps:")
print(array[0:4:2])

# 4. Print with negative steps
print("Range with negative indexing:")
print(array[::-1])

For 1st Row: [1 2 3 4]
For 2nd Row: [ 9 10 11 12]
Range of elements:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Range of elements with steps:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Range with negative indexing:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
import numpy as np

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# Coloumn selection.
# array[Row,Column]

# 1.select 1st column
print("First Column:")
print(array[:,0])

# 2.select first 2 elements from 1st Column
print("First 2 elements of the 1st column:")
print(array[0:2,0])

# 3.select last column using negative indexing
print("Last column using negative indexing:")
print(array[:,-1])

# 4.select range of columns
print("select range of columns:")
print(array[:,0:3])

# 5.select even columns
print("select even range of columns:")
print(array[:,1:4:2])  # or[::2]

# 6.select reverse columns
print("Reverse of columns:")
print(array[:,::-1])

# 7.select first 2 rows and first 2 columns
print("First two rows and first two column:")
print(array[0:2,0:2])
print("First two rows and last two column:")
print(array[0:2,2:4])

First Column:
[ 1  5  9 13]
First 2 elements of the 1st column:
[1 5]
Last column using negative indexing:
[ 4  8 12 16]
select range of columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
select even range of columns:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
Reverse of columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
First two rows and first two column:
[[1 2]
 [5 6]]
First two rows and last two column:
[[3 4]
 [7 8]]


**3. Arithmetic in Numpy**

 i. Scalar arithmetic

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
print("Addition:",array + 1)
print("Substraction:",array - 1)
print("Multiplication:",array * 3)
print("Division:",array / 4)
print("Power",array ** 2)

Addition: [2 3 4]
Substraction: [0 1 2]
Multiplication: [3 6 9]
Division: [0.25 0.5  0.75]
Power [1 4 9]


ii. Vectorized math function

In [ ]:
import numpy as np

# 1.Square root
array = np.array([1, 2, 3])
print("Square root:")
print(np.sqrt(array))

# 2.Round value
array2 = np.array([1.01, 2.54, 3.01])
print("Round value:")
print(np.round(array2))

# 3.Floor value(Round Down)
array3 = np.array([1.01, 2.54, 3.01])
print("Floor value:")
print(np.floor(array3))

# 4.Ceil value(Round Up)
array4 = np.array([1.01, 2.54, 3.01])
print("Ceil value:")
print(np.ceil(array4))

# 5. Pi value (Built in value)
print("Pi value:")
print(np.pi)

Square root:
[1.         1.41421356 1.73205081]
Round value:
[1. 3. 3.]
Floor value:
[1. 2. 3.]
Ceil value:
[2. 3. 4.]
Pi value:
3.141592653589793


In [ ]:
# Q-> Find area of circle whose radii are given.
import numpy as np

radii = np.array([1 ,2 , 3])
print("Area of circle for different radius:", np.pi * radii ** 2)

Area of circle for different radius: [ 3.14159265 12.56637061 28.27433388]


iii. Element-wise arithmetic

In [ ]:
import numpy as np

array1 = np.array([1 ,2 , 3])
array2 = np.array([4 ,5 , 6])

print("1.Addition :",array1 + array2)
print("2.Substraction :",array1 - array2)
print("3.Multiplication :",array1 * array2)
print("4.Division :",array1 / array2)
print("5.Power :",array1 ** array2)

1.Addition : [5 7 9]
2.Substraction : [-3 -3 -3]
3.Multiplication : [ 4 10 18]
4.Division : [0.25 0.4  0.5 ]
5.Power : [  1  32 729]


iv. Comparison Operators

In [ ]:
import numpy as np

# We can create Bollean Arrays , Filter Data  and Element wise comparisons

scores = np.array([91 , 55, 100, 73, 82, 64])
# 1.Scores 100 marks
print("1. Scores 100 marks :",scores == 100)
# 2.Scores greater than 60
print("2. Scores greater then 60 :",scores >= 60)
# 3.Scores less than 60
print("3. Scores less than 60 :",scores <= 60)
# 4.Assign 0 to those who scores less than 60
scores[scores < 60] = 0
print("4. Zero is assigned to those who scores less than 60 : ",scores)

1. Scores 100 marks : [False False  True False False False]
2. Scores greater then 60 : [ True False  True  True  True  True]
3. Scores less than 60 : [False  True False False False False]
4. Zero is assigned to those who scores less than 60 :  [ 91   0 100  73  82  64]


**4. Broadcasting in Numpy**

In [ ]:
"""Broadcasting allows NumPy to perform
operations on arrays with different
shapes by virtually expanding dimensions
so they match the larger array's shape"""
# The dimension have the same size.
# or
# One of the dimension has a size of 1.

In [ ]:
import numpy as np

array1 = np.array([[1 ,2 ,3 ,4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)
# The shape of two array should match or either one value should be 1.
# (1, 4)     or (4, 4)
# (4, 1)        (4, 4)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
# 1.Impossible Case
import numpy as np

array1 = np.array([[1 ,2 ,3 ,4],        # Not possible as shape = (2, 4)
                   [5, 6, 7, 8]])       #                         (4, 1)
array2 = np.array([[1], [2], [3], [4]])
print(array1 * array2)

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [ ]:
# 2.Possible case
import numpy as np

array1 = np.array([[1 ,2 ,3 ,4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], [2], [3], [4]])

print("Shape of arr1:",array1.shape)
print("Shape of arr2:",array2.shape)

print(array1 * array2)

Shape of arr1: (4, 4)
Shape of arr2: (4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


Q). Multiplication using Broadcasting

In [ ]:
import numpy as np

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])   # 1 row,10 column
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])   # 10 row ,1 column

print(array1.shape)
print(array2.shape)

print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


**5. Aggregate Function**

*(Aggregate function summarize data and typically return a single value)*

In [ ]:
import numpy as np

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
# 1.Sum Function.
print("Sum of all the numbers:",np.sum(array))

# 2.Mean Function.
print("Mean of all the numbers:",np.mean(array))

# 3.Standard Deviation
print("Standard deviation of all the numbers:",np.std(array))

# 4.Variance(Square of standard deviation)
print("variance of all the numbers:",np.var(array))

# 5.Minimum value
print("Minimum of all the values:",np.min(array))

# 6.Maximum value
print("Maximum of all the values:",np.max(array))

# 7.Argument Value(Specific position of a value (argmin/argmax))
print("Argument minimum values:",np.argmin(array))
print("Argument maximum values:",np.argmax(array))

# 8.For sum of all columns(For sum of all columns axis=0)
print("Sum of column values:",np.sum(array, axis = 0))

# 9.For sum of all rows(For sum of all rows axis=1)
print("Sum of row values:",np.sum(array, axis = 1))

Sum of all the numbers: 55
Mean of all the numbers: 5.5
Standard deviation of all the numbers: 2.8722813232690143
variance of all the numbers: 8.25
Minimum of all the values: 1
Maximum of all the values: 10
Argument minimum values: 0
Argument maximum values: 9
Sum of column values: [ 7  9 11 13 15]
Sum of row values: [15 40]


**6. Filtering in NumPy**

*(Filtering = Refers to the process of selecting elements from an array that match a given condition.)*

In [ ]:
import numpy as np

ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

# 1.Get teenagers whose age less than 18
teenagers = ages[ages < 18]
print("Teenagers",teenagers)

# 2.Get teenagers whose age greater than 18
adult = ages[(ages >= 18) & (ages < 65)]
print("Adults:",adult)

# 3.Get seniors whose age greater than 65.
seniors = ages[ages >= 65]
print("Seniors citizens:",seniors)

# 4.Even.
evens = ages[ages % 2 == 0]
print("Even ages people:",evens)

# 5.Odds.
odds = ages[ages % 2 != 0]
print("Odd ages people:",odds)

# To preserve the original shape of the array we use "where" function.
adults = np.where(ages >= 18, ages, 0)     # where(conditions, array, fill-value)
print("Adults with ages > 18:")
print(adults)

Teenagers [17 16 15]
Adults: [21 19 20 30 18 39 22 18 19 20 21]
Seniors citizens: [65 99]
Even ages people: [20 16 30 18 22 18 20]
Odd ages people: [21 17 19 65 39 15 99 19 21]
Adults with ages > 18:
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


**7. Random Number**

*(It is useful for simulations,modelling,applying random trasformations and testing purposes)*

In [ ]:
import numpy as np

rng = np.random.default_rng()

print("Random number: ",rng.integers(low=1, high=7))             # Range(start_Num, end_Num, size)
print("Two random numbers: ",rng.integers(low=1, high=7, size=2))     # To get random number more than 1 numbers we use 'size'.
print("Random 2D Array:")
print(rng.integers(low=1, high=7, size=(3,2))) # we can also create a range of 2D array
# we use random.uniform to get random floating values.
print("Random Floating point number:",np.random.uniform())
print("Random Floating point number from range:",np.random.uniform(low=-1, high=1))
print("Random Floating point number from range with different size:",np.random.uniform(low=-1, high=1 ,size = 2))
print("Random Floating point number from range with different size:")
print(np.random.uniform(low=-1, high=1 ,size = (2,2)))

Random number:  3
Two random numbers:  [3 6]
Random 2D Array:
[[2 2]
 [4 4]
 [4 1]]
Random Floating point number: 0.6113115380398411
Random Floating point number from range: -0.6859022004454007
Random Floating point number from range with different size: [ 0.43147413 -0.31219502]
Random Floating point number from range with different size:
[[-0.20132132 -0.30836788]
 [ 0.70341079  0.37944828]]


In [6]:
# Shuffle an array.
import numpy as np

rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print("Random numbers:",array)
array = rng.choice(array, size=(3,3))
print(array)

Random numbers: [1 4 3 5 2]
[[1 5 1]
 [4 3 1]
 [4 4 5]]
